name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the Platane Snake action with Docker
      - name: Generate snake.svg with docker
        uses: Platane/snk@v3  # Make sure you're on the latest v3 version
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          
      # Push the generated `snake.svg` to the `output` branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # Where GitHub Pages is served from
          build_dir: dist  # Directory where the SVG is saved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
